### ISSUE TITLE
Keyboard shortcuts conflicts with czech keyboard

### ISSUE THREAD

**Issue by michalwiglasz** [duydao/Text-Pastry#25]
I'm used to Czech keyboard which uses combinations with `AltGr` (right alt, equivalent to `Ctrl+Alt`) to write some special chars. For example `AltGr + B` (or `Ctrl + Alt + B`) means `{`. 

TextPastry's default keymap conflicts with these, so I'm unable to write those special chars.

Can you please make these keyboard shortcuts optional?

**Comment by stevepowell99** [comment]
I have exactly the same conflict with altgr-b. I followed your advice - I already had that folder and file, tried deleting the entries and redefining them as unbound, etc, but nothing worked. Tried this too: http://stackoverflow.com/questions/19245837/how-to-unbind-a-key-binding-in-sublime-text-2. Uninstalled textpastry, what a shame, because very useful.
