### ISSUE TITLE
Unable to change shorcut for "text_pastry_show_command_line", ST 3.1.1 Build 3176

### ISSUE THREAD

**Issue by carlos-rosas** [duydao/Text-Pastry#77]
I've trying to disable default keys for this command by overwriting on Default (Windows).sublime-keymap:
`{ "keys": ["ctrl+k", "ctrl+p"], "command": "text_pastry_show_command_line", "args": { "text": "" } },`

Those changes works, but when I type:
`["ctrl+alt+n"],` or `["alt+n"],`

Always shows "Text Pastry Command".

I use a US-International keyboard layout, and frecuently use `["alt+n"],` just to write ñ.

**Comment by caverus** [comment]
I use this as a workaround:

`{ "keys": ["ctrl+alt+n"], "command": "insert", "args": {"characters": "ń"}  },
	{ "keys": ["ctrl+shift+y"], "command": "text_pastry_show_command_line", "args": { "text": "" }}`

**Comment by duydao** [comment]
@carlos-rosas Unfortunately, adding the keymap in your user keymap file does not overwrite the key binding, it adds another one. In order to remote the key binding of text pastry, you would have to edit the file that comes with the Text Pastry package. Please reopen this issue if the workaround from @caverus fails.

Thanks for using Text Pastry!
