### ISSUE TITLE
Issues working with Improved paste (paste the first three lines of the clipboard data to the three selected locations)

### ISSUE THREAD

**Issue by stdedos** [duydao/Text-Pastry#89]
As per README.md:

> Improved paste (paste the first three lines of the clipboard data to the three selected locations)

and, I guess it's the same as:

> Paste as Block

I think it used to be working, but now I cannot get it to work.

The intention is to copy this:

```

      <param name="a">b</param>
```

to go from this:
```
      <param name="1">2</param>


      <param name="3">4</param>
```

to this:
```
      <param name="1">2</param>
      <param name="a">b</param>


      <param name="3">4</param>
      <param name="a">b</param>
```

However, none of the commands:

- TextPastry: Paste
- TextPastry: Paste Lines
- `regex $` 
- "repeat_clipboard": true,
- "clipboard_strip_newline": false,

can get me to the desired result cleanly.

After all of the above, the closest I get is this:
```
      <param name="1">2</param>
<param name="a">b</param>


      <param name="3">4</param>
<param name="a">b</param>
```

I was wondering if you could help, expand documentation, and/or fix a behavior if it's problematic.

**Comment by duydao** [comment]
Hi!

thanks for using Text Pastry!

Paste as block should take every line of the clipboard and treats it as a queue. If we copy a block like this
```
first line
second line
third line
```

and paste it into this selection
```
<a>|</a>
<b>|</b>
<i>|</i>
```

we would get this:
```
<a>first line</a>
<b>second line</b>
<i>third line</i>
```

instead of this:
```
<a>first line
second line
third line</a>
<b>first line
second line
third line</b>
<i>first line
second line
third line</i>
```

may I ask you for a different example of your use-case?

**Comment by stdedos** [comment]
Perhaps I haven't been clear enough, apologies. I am not _that_ familiar with the finer details of the plugin. 

I want to use TextPastry's feature that will help me treat the copied text "as one entity", instead of splitting it as newlines. 

i.e. If I copy 2 lines and have 2 carets, I expect to paste 2 lines on both carets, instead of one each.

**Comment by duydao** [comment]
Thanks for taking your time to clarify this issue.

This should already be a default feature of sublime text!

Expanding on your example, if we copy this line into the clipboard:

```
      <param name="a">b</param>
```


we can paste it normally and it will be inserted on every location with a caret, as this clip shows:

![paste](https://user-images.githubusercontent.com/1011201/119266103-bdbd3580-bbe9-11eb-988d-3cf6b531b33d.gif)

Would that the feature, that you were looking for?

**Comment by stdedos** [comment]
Thank you for your quick response. Please note that my example is not this:

> ```
>       <param name="a">b</param>
> ```

but it's that:

> ```
> 
>       <param name="a">b</param>
> ```

(i.e. one extra `\n`)

**Comment by duydao** [comment]
Thank you for clarifying the issue!

The content shouldn't matter, as long as we paste using the default paste (ctrl+v or cmd+v), the text will be pasted into the selected location by sublime text, as shown in this clip:

![paste2](https://user-images.githubusercontent.com/1011201/119266810-82703600-bbec-11eb-9244-eac80cc6ce11.gif)

Please let me know if we're on the right track on this issue!

**Comment by stdedos** [comment]
Again, you are making a different selection 😂

**Comment by duydao** [comment]
Ah, your example does does not select the new line character at the end.

This is a "feature"/bug in sublime text and it only happens, when the selection count matches the pasted content split by newline. If I would've select three instances of the `</param>` endtag, instead of two, it would behave oddly aswell. Even when I've disable/uninstall Text Pastry, we would still have this behaviour (please feel free to confirm this behaviour).

It works in my example because I was selecting an additional newline, which made the number of carets mismatch with the pasted content. This would also be the workaround: it should work if we paste the content into more selections/carets. Maybee there is a bugfix in the latest version of Sublime Text, that would be worth a shot.

I've checked the sources of text pastry, and unfortunately we don't have an option to paste "as is" atm. option. I will check the conditions to add such a feature.

Thanks for using text pastry!
