### ISSUE TITLE
Key-bind conflict

### ISSUE THREAD

**Issue by floq-design** [duydao/Text-Pastry#93]
I discovered today that a custom key binding of mine to toggle the sidebar is in conflict with a Text Pastry command.
`{ "keys": ["ctrl+s"], "command": "toggle_side_bar" },`
Sublime's console logs the command as `text_pastry_cancel`...
```
command: toggle_side_bar
command: toggle_side_bar {"event": {"modifier_keys": {"ctrl": true}}}
plugin rewritten command: text_pastry_cancel
```
When I goto the default Text Pastry keymap - there is no command by that name listed.

I've tried adding:
`{ "keys": ["super+alt+ctrl+c"], "command": "text_pastry_cancel" }`
to my user key-bindings but that doesn't over-ride it.
Even if I change my key-binding to say `"ctrl+alt+s"` - it's still in conflict?
Oddness.

**Comment by mcaskill** [comment]
I'm having the same issue with Sublime Text 4121.

```
{ "keys": [ "super+`" ], "command": "toggle_side_bar" }
```

```
command: toggle_side_bar
command: toggle_side_bar {"event": {"modifier_keys": {"primary": true, "super": true}}}
plugin rewritten command: text_pastry_cancel
```

**Comment by Vanderhoof** [comment]
Here's the [line](https://github.com/duydao/Text-Pastry/blob/master/text_pastry_addons.py#L49) where this happens. I have no idea why this is needed, but since the author ignores the issue, here's a quick dirty fix:

1. Press CTRL+SHIFT+P and find command `PackageResourceViewer: Extract package`. Press enter.
2. Select TextPastry and press enter, then enter again on "start extraction"
3. In top menu select Preferences -> Browse packages
4. In Text Pastry folder open `text_pastry_addons.py` end edit this line:

```python
class TextPastryPanelListener(sublime_plugin.EventListener):
    listener = ['toggle_side_bar', 'toggle_status_bar', 'toggle_tabs', 'toggle_minimap']  # <------ this line
    running = False
```

Just remove the `'toggle_side_bar'` from the list so that this line looks like this:

```python
    listener = ['toggle_status_bar', 'toggle_tabs', 'toggle_minimap']
```

Save the file and the problem is gone.
